// server/modules/simulation/models/SimulationPlan.js
//
// S.7.7+ обновления:
//   • LandmarkSchema.mediapipeIndex — расширен с 0..467 до 0..477 (478 точек)
//   • LandmarkSchema.group — расширен enum: forehead, chin, cheeks, jaws, manual, ears
//   • landmarks array length — relaxed validator (0..2000) после убирания anatomy
//     с frontend в Phase Б.2 v3 minimal. Старый whitelist [0,6,468,478] reject'ил
//     планы с partial landmarks данными в БД.
//   • LandmarksMetaSchema — добавлены: source, facesDetected, selectedFaceIndex,
//     rotationUsed (для multi-face и rotation retry)
//   • LandmarksMetaSchema.pointsCount — расширен до 478

import mongoose from "mongoose";

const { Schema } = mongoose;

/* ──────────────────────────────────────────────────────────────────────────
   Photo schema
   ────────────────────────────────────────────────────────────────────────── */
const PhotoSchema = new Schema(
  {
    url: { type: String, required: true },
    r2Key: { type: String, default: null },
    width: { type: Number, default: null, min: 1, max: 20000 },
    height: { type: Number, default: null, min: 1, max: 20000 },
    photoView: { type: String, default: "front" },
  },
  { _id: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   Control point (без изменений)
   ────────────────────────────────────────────────────────────────────────── */
const ControlPointSchema = new Schema(
  {
    key: { type: String, required: true },
    anchor: {
      x: { type: Number, required: true, min: 0, max: 1 },
      y: { type: Number, required: true, min: 0, max: 1 },
    },
    current: {
      x: { type: Number, required: true, min: 0, max: 1 },
      y: { type: Number, required: true, min: 0, max: 1 },
    },
    radius: { type: Number, required: true, min: 0.001, max: 1 },
    strength: { type: Number, required: true, min: -1, max: 1 },
  },
  { _id: false, strict: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   Anatomical landmark (S.7) — точка из MediaPipe или ручной разметки.
   ────────────────────────────────────────────────────────────────────────── */
const LandmarkSchema = new Schema(
  {
    id: { type: String, required: true },
    mediapipeIndex: { type: Number, required: true, min: -1, max: 477 },
    group: {
      type: String,
      required: true,
      enum: [
        "face_oval",
        "forehead",
        "nose",
        "lips",
        "left_eye",
        "right_eye",
        "left_eyebrow",
        "right_eyebrow",
        "left_cheek",
        "right_cheek",
        "left_jaw",
        "right_jaw",
        "chin",
        "ears",
        "manual",
        "other",
      ],
    },
    x: { type: Number, required: true, min: 0, max: 1 },
    y: { type: Number, required: true, min: 0, max: 1 },
    z: { type: Number, default: 0 },
    autoGenerated: { type: Boolean, default: true },
    source: { type: String, default: null, maxlength: 32 },
    hidden: { type: Boolean, default: false },
  },
  { _id: false, strict: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   LandmarksMeta — без изменений
   ────────────────────────────────────────────────────────────────────────── */
const LandmarksMetaSchema = new Schema(
  {
    detectedAt: { type: Date, default: null },
    modelVersion: { type: String, default: null, maxlength: 64 },
    imageWidth: { type: Number, default: null, min: 1, max: 20000 },
    imageHeight: { type: Number, default: null, min: 1, max: 20000 },
    pointsCount: { type: Number, default: 0, min: 0, max: 600 },

    source: {
      type: String,
      default: "auto",
      enum: ["auto", "manual_fit"],
    },
    facesDetected: { type: Number, default: 0, min: 0, max: 10 },
    selectedFaceIndex: { type: Number, default: 0, min: 0, max: 9 },
    rotationUsed: {
      type: Number,
      default: 0,
      enum: [0, 90, 180, 270],
    },
    anchorCount: { type: Number, default: 0, min: 0, max: 50 },
  },
  { _id: false, strict: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   SimulationPlan — основная схема.

   Validator landmarks смягчён до диапазона 0..2000 после убирания anatomy
   разметки с frontend. Раньше whitelist'ил только [0, 6, 468, 478] что
   ломало update планов с partial landmarks данными.
   ────────────────────────────────────────────────────────────────────────── */
const SimulationPlanSchema = new Schema(
  {
    doctorId: {
      type: Schema.Types.ObjectId,
      required: true,
      index: true,
    },

    labelEncrypted: { type: String, required: true },
    patientRefEncrypted: { type: String, default: null },

    photoView: { type: String, default: "front" },
    photo: { type: PhotoSchema, required: true },

    // Anatomy / operation / calibration — Mixed для будущего использования.
    // Frontend больше не отправляет, но БД сохраняет для совместимости.
    anatomy: { type: Schema.Types.Mixed, default: () => ({}) },
    operation: { type: Schema.Types.Mixed, default: () => ({}) },
    calibration: { type: Schema.Types.Mixed, default: () => ({}) },

    controlPoints: { type: [ControlPointSchema], default: [] },

    // Landmarks — relaxed validator
    landmarks: {
      type: [LandmarkSchema],
      default: [],
      validate: {
        validator: (arr) =>
          Array.isArray(arr) && arr.length >= 0 && arr.length <= 2000,
        message: "landmarks must be array of 0..2000 elements",
      },
    },
    landmarksMeta: {
      type: LandmarksMetaSchema,
      default: () => ({}),
    },

    deletedAt: { type: Date, default: null },
  },
  {
    timestamps: true,
    collection: "simulation_plans",
    strict: false,
  },
);

SimulationPlanSchema.index({ doctorId: 1, createdAt: -1 });
SimulationPlanSchema.index({ doctorId: 1, deletedAt: 1 });

const SimulationPlan =
  mongoose.models.SimulationPlan ||
  mongoose.model("SimulationPlan", SimulationPlanSchema);

export default SimulationPlan;
