// server/modules/simulation/models/SimulationPlan.js
import mongoose from "mongoose";

const { Schema } = mongoose;

/* ──────────────────────────────────────────────────────────────────────────
   Control point: нормализованные координаты в [0..1], разрешение-независимо.
   anchor   — исходное положение точки (не двигается)
   current  — куда точку оттащил врач (deformation target)
   radius   — радиус влияния в нормализованном пространстве [0.001..1]
   strength — сила деформации [-1..1], отрицательное = push away от anchor
   ────────────────────────────────────────────────────────────────────────── */
const ControlPointSchema = new Schema(
  {
    key: { type: String, required: true },
    anchor: {
      x: { type: Number, required: true, min: 0, max: 1 },
      y: { type: Number, required: true, min: 0, max: 1 },
    },
    current: {
      x: { type: Number, required: true, min: 0, max: 1 },
      y: { type: Number, required: true, min: 0, max: 1 },
    },
    radius: { type: Number, required: true, min: 0.001, max: 1 },
    strength: { type: Number, required: true, min: -1, max: 1 },
  },
  { _id: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   Anatomical landmark (S.7) — авто или ручная точка.

   - MediaPipe FaceLandmarker (478 точек: 468 базовых + 10 для радужек).
   - Ручные точки: mediapipeIndex = -1, group = "manual".

   id              — стабильный идентификатор 'lm_<index>' / 'lm_manual_<n>'
   mediapipeIndex  — -1 для manual, 0..477 для MediaPipe (с iris)
   group           — анатомическая группа (16 вариантов)
   x, y            — нормализованные [0..1] относительно изображения
   z               — глубина (отн. единицы, опциональна)
   autoGenerated   — true = MediaPipe, false = ручная
   hidden          — true = точка скрыта в UI

   _id: false — на сотни точек MongoDB ObjectId дал бы +9KB на план;
                уникальность обеспечивается полем id.
   ────────────────────────────────────────────────────────────────────────── */
const LandmarkSchema = new Schema(
  {
    id: { type: String, required: true },
    mediapipeIndex: { type: Number, required: true, min: -1, max: 477 },
    group: {
      type: String,
      required: true,
      enum: [
        "face_oval",
        "nose",
        "lips",
        "left_eye",
        "right_eye",
        "left_eyebrow",
        "right_eyebrow",
        "forehead",
        "left_cheek",
        "right_cheek",
        "left_jaw",
        "right_jaw",
        "chin",
        "ears",
        "manual",
        "other",
      ],
    },
    x: { type: Number, required: true, min: 0, max: 1 },
    y: { type: Number, required: true, min: 0, max: 1 },
    z: { type: Number, required: false, default: 0 },
    autoGenerated: { type: Boolean, default: true },
    hidden: { type: Boolean, default: false },
  },
  { _id: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   Метаданные о последней детекции landmarks.
   Нужны для калибровки (S.7.6 — мм через известное расстояние) и
   отслеживания версии модели на случай обновлений MediaPipe.

   detectedAt    — таймстамп успешной детекции
   modelVersion  — например 'mediapipe@0.10.18'
   imageWidth/H  — пиксельный размер фото в момент детекции
                   (если фото перезалили — landmarks нужно пересчитать)
   pointsCount   — длина массива landmarks для быстрых выборок
   ────────────────────────────────────────────────────────────────────────── */
const LandmarksMetaSchema = new Schema(
  {
    detectedAt: { type: Date, default: null },
    modelVersion: { type: String, default: null, maxlength: 64 },
    imageWidth: { type: Number, default: null, min: 1, max: 20000 },
    imageHeight: { type: Number, default: null, min: 1, max: 20000 },
    pointsCount: { type: Number, default: 0, min: 0, max: 600 },
  },
  { _id: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   Embedded photo — никаких ссылок на внешние коллекции.
   r2Key — внутренний ключ в R2 bucket (для delete при удалении плана)
   url   — публичный URL, отдаваемый клиенту
   ────────────────────────────────────────────────────────────────────────── */
const PhotoSchema = new Schema(
  {
    r2Key: { type: String, required: true },
    url: { type: String, required: true },
    width: { type: Number, required: true, min: 1 },
    height: { type: Number, required: true, min: 1 },
    size: { type: Number, required: true, min: 0 },
    mimeType: { type: String, required: true },
    uploadedAt: { type: Date, required: true, default: Date.now },
  },
  { _id: false },
);

const SimulationPlanSchema = new Schema(
  {
    doctorId: {
      type: Schema.Types.ObjectId,
      required: true,
      index: true,
    },

    // Отображаемое имя плана — зашифровано (PHI-смежные данные).
    labelEncrypted: { type: String, required: true },

    // Опциональная метка пациента, выбранная врачом. Тоже зашифрована.
    patientRefEncrypted: { type: String, default: null },

    photo: { type: PhotoSchema, required: true },
    controlPoints: { type: [ControlPointSchema], default: [] },

    // ── S.7 — automated anatomical landmarks ───────────────────────────
    // Массив 0..600 точек: пустой (детекция не запускалась/провалилась),
    // 478 от MediaPipe (468 base + 10 iris), плюс возможные ручные.
    landmarks: {
      type: [LandmarkSchema],
      default: [],
      validate: {
        validator: (arr) => arr.length >= 0 && arr.length <= 600,
        message: "landmarks must contain between 0 and 600 points",
      },
    },
    landmarksMeta: {
      type: LandmarksMetaSchema,
      default: () => ({}),
    },

    // Soft delete. R2-объект чистится в deletePlanController.
    deletedAt: { type: Date, default: null },
  },
  {
    timestamps: true, // createdAt, updatedAt
    collection: "simulation_plans",
  },
);

// Основной индекс: список планов врача, свежие сверху.
SimulationPlanSchema.index({ doctorId: 1, createdAt: -1 });

// Фильтр live/удалённых, плюс admin cleanup / восстановление.
SimulationPlanSchema.index({ doctorId: 1, deletedAt: 1 });

// TTL на soft-deleted старше 30 дней — раскомментировать при желании.
// SimulationPlanSchema.index({ deletedAt: 1 }, { expireAfterSeconds: 60 * 60 * 24 * 30 });

const SimulationPlan = mongoose.model("SimulationPlan", SimulationPlanSchema);

export default SimulationPlan;
