// server/modules/simulation/models/SimulationPlan.js
//
// УНИВЕРСАЛЬНАЯ модель для всех типов симуляции.
//
// Принцип: НЕ используем mongoose discriminator (он ломает legacy документы и
// требует миграций при добавлении новых типов). Вместо этого:
//   • planType — обычный enum string. Любое значение можно добавить тут.
//   • anatomy — Schema.Types.Mixed. Любая структура anatomical points
//                в зависимости от типа. Frontend знает какая.
//   • operation — Schema.Types.Mixed. Параметры конкретной операции.
//   • calibration — общая структура (px → mm), применима ко всем типам.
//
// Преимущества:
//   ✅ Старые face документы (без planType) работают без миграций.
//   ✅ Добавление нового типа (abdomen, arms, thighs, ...) = одна строка
//      в SUPPORTED_PLAN_TYPES.
//   ✅ Frontend контролирует структуру anatomy/operation для каждого типа.
//   ✅ Joi валидация на API-уровне обеспечивает type safety.
//
// Trade-off:
//   • Менее строгая mongoose-валидация структуры anatomy (Mixed).
//     Это сознательное решение — гибкость > строгость.
//   • Frontend ОБЯЗАН валидировать данные перед отправкой.

import mongoose from "mongoose";

const { Schema } = mongoose;

/* ──────────────────────────────────────────────────────────────────────────
   Поддерживаемые типы планов. Чтобы добавить новый — добавь сюда.
   "face" — default для старых документов где поля planType нет.
   ────────────────────────────────────────────────────────────────────────── */
export const SUPPORTED_PLAN_TYPES = [
  "face",
  "breast",
  // Будущее:
  "abdomen",
  "arms",
  "thighs",
  "back",
  "buttocks",
  "neck",
  "ears",
  "eyes",
  "lips",
];

/* ──────────────────────────────────────────────────────────────────────────
   Control point — общий для всех типов (warp engine использует одинаково).
   ────────────────────────────────────────────────────────────────────────── */
const ControlPointSchema = new Schema(
  {
    key: { type: String, required: true },
    anchor: {
      x: { type: Number, required: true, min: 0, max: 1 },
      y: { type: Number, required: true, min: 0, max: 1 },
    },
    current: {
      x: { type: Number, required: true, min: 0, max: 1 },
      y: { type: Number, required: true, min: 0, max: 1 },
    },
    radius: { type: Number, required: true, min: 0.001, max: 1 },
    strength: { type: Number, required: true, min: -1, max: 1 },
  },
  { _id: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   Anatomical landmark (face-specific, MediaPipe).
   Используется ТОЛЬКО для face планов. Для других типов — пустой массив.
   ────────────────────────────────────────────────────────────────────────── */
const LandmarkSchema = new Schema(
  {
    id: { type: String, required: true },
    mediapipeIndex: { type: Number, required: true, min: -1, max: 477 },
    group: {
      type: String,
      required: true,
      enum: [
        "face_oval",
        "forehead",
        "nose",
        "lips",
        "left_eye",
        "right_eye",
        "left_eyebrow",
        "right_eyebrow",
        "left_cheek",
        "right_cheek",
        "left_jaw",
        "right_jaw",
        "chin",
        "ears",
        "manual",
        "other",
      ],
    },
    x: { type: Number, required: true, min: 0, max: 1 },
    y: { type: Number, required: true, min: 0, max: 1 },
    z: { type: Number, default: 0 },
    autoGenerated: { type: Boolean, default: true },
    source: { type: String, default: null, maxlength: 32 },
    hidden: { type: Boolean, default: false },
  },
  { _id: false },
);

const LandmarksMetaSchema = new Schema(
  {
    detectedAt: { type: Date, default: null },
    modelVersion: { type: String, default: null, maxlength: 64 },
    imageWidth: { type: Number, default: null, min: 1, max: 20000 },
    imageHeight: { type: Number, default: null, min: 1, max: 20000 },
    pointsCount: { type: Number, default: 0, min: 0, max: 478 },
    source: {
      type: String,
      default: "auto",
      enum: ["auto", "manual_fit"],
    },
    facesDetected: { type: Number, default: 0, min: 0, max: 10 },
    selectedFaceIndex: { type: Number, default: 0, min: 0, max: 9 },
    rotationUsed: {
      type: Number,
      default: 0,
      enum: [0, 90, 180, 270],
    },
    anchorCount: { type: Number, default: 0, min: 0, max: 20 },
  },
  { _id: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   Photo (общая для всех типов).
   ────────────────────────────────────────────────────────────────────────── */
const PhotoSchema = new Schema(
  {
    r2Key: { type: String, required: true },
    url: { type: String, required: true },
    width: { type: Number, required: true, min: 1 },
    height: { type: Number, required: true, min: 1 },
    size: { type: Number, required: true, min: 0 },
    mimeType: { type: String, required: true },
    uploadedAt: { type: Date, required: true, default: Date.now },
  },
  { _id: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   Calibration (общая) — px → mm пересчёт.
   p1, p2 — две точки на фото с известным расстоянием в мм.
   ────────────────────────────────────────────────────────────────────────── */
const CalibrationSchema = new Schema(
  {
    knownDistanceMm: { type: Number, default: null, min: 1, max: 1000 },
    p1: {
      x: { type: Number, default: null, min: 0, max: 1 },
      y: { type: Number, default: null, min: 0, max: 1 },
    },
    p2: {
      x: { type: Number, default: null, min: 0, max: 1 },
      y: { type: Number, default: null, min: 0, max: 1 },
    },
    referenceLabel: { type: String, default: "", maxlength: 100 },
  },
  { _id: false },
);

/* ──────────────────────────────────────────────────────────────────────────
   Допустимые длины массива landmarks (face only).
   ────────────────────────────────────────────────────────────────────────── */
const ALLOWED_LANDMARK_LENGTHS = new Set([0, 1, 6, 468, 478]);

/* ──────────────────────────────────────────────────────────────────────────
   Главная schema — единая для всех типов.
   ────────────────────────────────────────────────────────────────────────── */
const SimulationPlanSchema = new Schema(
  {
    doctorId: {
      type: Schema.Types.ObjectId,
      required: true,
      index: true,
    },

    // S.8 — Тип симуляции. Default "face" для backwards compat.
    // Чтобы добавить новый тип — расширь SUPPORTED_PLAN_TYPES выше.
    planType: {
      type: String,
      enum: SUPPORTED_PLAN_TYPES,
      default: "face",
      index: true,
    },

    // S.8 — Ракурс фото (для multi-view типов: breast, abdomen, arms).
    // Для face — null (один ракурс на план).
    photoView: {
      type: String,
      default: null,
      maxlength: 32,
    },

    labelEncrypted: { type: String, required: true },
    patientRefEncrypted: { type: String, default: null },

    photo: { type: PhotoSchema, required: true },
    controlPoints: { type: [ControlPointSchema], default: [] },

    // S.8 — Универсальные anatomy points. Структура зависит от planType.
    // Frontend знает что куда класть, mongoose не валидирует структуру.
    // Schema.Types.Mixed — любой JSON.
    anatomy: {
      type: Schema.Types.Mixed,
      default: {},
    },

    // S.8 — Параметры операции. Структура зависит от planType.
    operation: {
      type: Schema.Types.Mixed,
      default: { type: null },
    },

    // Калибровка px → mm. Общая структура для всех типов.
    calibration: {
      type: CalibrationSchema,
      default: () => ({}),
    },

    // Face-specific (для других типов остаются пустыми).
    landmarks: {
      type: [LandmarkSchema],
      default: [],
      validate: {
        validator: (arr) => ALLOWED_LANDMARK_LENGTHS.has(arr.length),
        message: "landmarks must be 0, 1, 6, 468, or 478",
      },
    },
    landmarksMeta: {
      type: LandmarksMetaSchema,
      default: () => ({}),
    },

    deletedAt: { type: Date, default: null },
  },
  {
    timestamps: true,
    collection: "simulation_plans",
    // strict: true (default) — но Mixed поля принимают любые данные.
    // Минимальная инвазивность для legacy документов:
    minimize: false, // не удаляет пустые объекты
  },
);

SimulationPlanSchema.index({ doctorId: 1, createdAt: -1 });
SimulationPlanSchema.index({ doctorId: 1, deletedAt: 1 });
SimulationPlanSchema.index({ doctorId: 1, planType: 1, deletedAt: 1 });

const SimulationPlan = mongoose.model("SimulationPlan", SimulationPlanSchema);

export default SimulationPlan;
