// server/modules/clinic/clinic-patients/routes/consentRequest.routes.js
//
// Routes for CLINIC-SIDE consent request management.
// Sprint 3.2 (Pull Consent, 31 May 2026).
//
// Mount path (from parent clinic router): /api/v1/clinic/*
// Final URLs:
//   POST   /api/v1/clinic/patients/:cardId/consent-requests
//   GET    /api/v1/clinic/patients/:cardId/consent-requests
//   DELETE /api/v1/clinic/consent-requests/:id
//
// tenantMiddleware and session are applied at parent router level —
// we don't repeat them here. Mirrors patient.routes.js pattern.
//
// AUDIT:
//   • GET (list)    → middleware (resourceId not required for collection reads)
//   • POST (create) → NO middleware, audit happens inside service (resourceId
//                     generated by service; mirrors patient.routes.js create pattern)
//   • DELETE        → middleware (resourceId from params.id)

import express from "express";
import * as ctrl from "../controllers/consentRequest.clinic.controller.js";
import auditMiddleware from "../../../audit/middleware/auditMiddleware.js";

const router = express.Router();

// ─── POST /clinic/patients/:cardId/consent-requests ───────────────────
// NO auditMiddleware — audit recorded inside consentRequestService.createRequest
// AFTER the request._id is generated. Same pattern as POST /patients.
router.post("/patients/:cardId/consent-requests", ctrl.createConsentRequest);

// ─── GET /clinic/patients/:cardId/consent-requests ────────────────────
// List history of requests this clinic made for this patient.
// resourceId not applicable for collection reads.
router.get(
  "/patients/:cardId/consent-requests",
  auditMiddleware({
    resourceType: "consent-request",
    action: "consent_request.list",
    metaFrom: (req) => ({
      cardId: req.params?.cardId || null,
    }),
  }),
  ctrl.listConsentRequestsForPatient,
);

// ─── DELETE /clinic/consent-requests/:id ──────────────────────────────
// Clinic cancels its own pending request before patient responded.
router.delete(
  "/consent-requests/:id",
  auditMiddleware({
    resourceType: "consent-request",
    action: "consent_request.cancel",
    resourceIdFrom: "params.id",
  }),
  ctrl.cancelConsentRequest,
);

export default router;
