// server/modules/clinic/clinic-patients/routes/patient.routes.js
//
// REST endpoints for ClinicPatient CRUD + search + link.
//
// Mount path (from parent clinic router): /api/v1/clinic/*
// Final URLs:
//   GET    /api/v1/clinic/patients/search
//   GET    /api/v1/clinic/patients
//   POST   /api/v1/clinic/patients
//   GET    /api/v1/clinic/patients/:id
//   PATCH  /api/v1/clinic/patients/:id
//   DELETE /api/v1/clinic/patients/:id
//   POST   /api/v1/clinic/patients/:id/link
//   DELETE /api/v1/clinic/patients/:id/link
//
// tenantMiddleware and session middleware are applied at the parent
// router level — we don't repeat them here.
//
// AUDIT MIDDLEWARE (HIPAA §164.312(b)):
//   Every endpoint is wrapped with auditMiddleware that records to the
//   hipaa_audit_logs collection. Recorded:
//     - WHO (actor: userId, email, role) — from req.user/req.session
//     - WHAT (action: clinic.patient.*) — explicit per route
//     - ON WHAT (resourceType: clinic-patient, resourceId from path or null)
//     - WHEN (timestamp — auto)
//     - OUTCOME (success | denied | failure — derived from status code)
//     - WHERE (IP, userAgent, requestId — auto)
//     - METADATA (per route, NEVER includes PHI — only counts/types/flags)
//
//   PHI safety rule for metaFrom: NEVER include firstName, lastName,
//   phone, email, dateOfBirth, notes, or any decrypted content. Audit
//   log must NOT duplicate PHI — otherwise a leaked audit log =
//   leaked patient database. Only safe to log: field names (not
//   values), counts, type enums, booleans.

import express from "express";
import * as ctrl from "../controllers/patient.controller.js";
import auditMiddleware from "../../../audit/middleware/auditMiddleware.js";

const router = express.Router();

// ─── Search ───────────────────────────────────────────────────────────
// MUST come before /patients/:id — otherwise "search" is matched as :id.
// We log WHAT TYPE of search was performed (phone/email/lastName), not
// the search value itself — search terms can be PHI.
router.get(
  "/patients/search",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.search",
    metaFrom: (req) => ({
      searchedBy: req.query?.phone
        ? "phone"
        : req.query?.email
          ? "email"
          : req.query?.lastName
            ? "lastName"
            : "unknown",
      limit: Number(req.query?.limit) || 20,
    }),
  }),
  ctrl.searchPatients,
);

// ─── List ─────────────────────────────────────────────────────────────
// No resourceId — this is a collection read. Meta captures pagination
// params (limit, cursor presence) for usage analytics, no PHI.
router.get(
  "/patients",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.list",
    metaFrom: (req) => ({
      limit: Number(req.query?.limit) || 50,
      hasBefore: Boolean(req.query?.before),
      sortBy: req.query?.sortBy || "createdAt",
    }),
  }),
  ctrl.listPatients,
);

// ─── Create ───────────────────────────────────────────────────────────
// resourceId not available at this point — the new patient ID is
// generated by the service after middleware mounts. Mongo's audit log
// captures the user, timestamp, and outcome — that's sufficient for
// "show me who created patients last week" queries. To find the actual
// patient created, query by timestamp + actor.
//
// Meta captures only structural info — which optional fields were
// present, gender (low-sensitivity demographic). Never the actual
// name/phone/email values.
router.post(
  "/patients",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.create",
    metaFrom: (req) => ({
      hasPhone: Boolean(req.body?.phone),
      hasEmail: Boolean(req.body?.email),
      hasDateOfBirth: Boolean(req.body?.dateOfBirth),
      hasNotes: Boolean(req.body?.notes),
      gender: req.body?.gender || null,
    }),
  }),
  ctrl.createPatient,
);

// ─── Read by ID ───────────────────────────────────────────────────────
// Core HIPAA event — "doctor X accessed patient Y's record". This is
// what auditors care about most. resourceId is the patient ID.
router.get(
  "/patients/:id",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.read",
    resourceIdFrom: "params.id",
  }),
  ctrl.getPatient,
);

// ─── Update ───────────────────────────────────────────────────────────
// Meta captures WHICH fields changed (by name) — useful for audit
// reviews. NEVER captures the values (those are PHI). Example log
// after an update: { fieldsChanged: ["phone", "email"] } — we know
// the contact info was changed but not to what.
router.patch(
  "/patients/:id",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.update",
    resourceIdFrom: "params.id",
    metaFrom: (req) => ({
      fieldsChanged: Object.keys(req.body || {}),
    }),
  }),
  ctrl.updatePatient,
);

// ─── Delete (soft) ────────────────────────────────────────────────────
// Critical event — deletion of a PHI record. Always audited.
// Note: this is soft-delete (isDeleted: true), record stays in DB.
router.delete(
  "/patients/:id",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.delete",
    resourceIdFrom: "params.id",
  }),
  ctrl.deletePatient,
);

// ─── Link to DocPats user ─────────────────────────────────────────────
// Sensitive operation — gives a DocPats user account access to this
// patient's record. resourceOwnerId captures WHICH user got linked
// (important for "show me everyone linked to user X's account").
router.post(
  "/patients/:id/link",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.link",
    resourceIdFrom: "params.id",
    resourceOwnerIdFrom: (req) => req.body?.userId,
  }),
  ctrl.linkPatient,
);

// ─── Unlink ───────────────────────────────────────────────────────────
// Inverse of link. The unlinked userId is in the patient doc, not in
// the request — so we can't capture resourceOwnerId at middleware
// level. The action itself + patient ID is sufficient for forensics
// (full state available by querying patient_link history).
router.delete(
  "/patients/:id/link",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.unlink",
    resourceIdFrom: "params.id",
  }),
  ctrl.unlinkPatient,
);

export default router;
