// server/modules/clinic/clinic-patients/routes/patient.routes.js
//
// REST endpoints for ClinicPatient CRUD + search + link + user-search.
//
// Mount path (from parent clinic router): /api/v1/clinic/*
// Final URLs:
//   GET    /api/v1/clinic/patients/search
//   GET    /api/v1/clinic/patients/users/search
//   GET    /api/v1/clinic/patients
//   POST   /api/v1/clinic/patients
//   GET    /api/v1/clinic/patients/:id
//   PATCH  /api/v1/clinic/patients/:id
//   DELETE /api/v1/clinic/patients/:id
//   POST   /api/v1/clinic/patients/:id/link
//   DELETE /api/v1/clinic/patients/:id/link
//
// tenantMiddleware and session middleware are applied at the parent
// router level — we don't repeat them here.
//
// AUDIT MIDDLEWARE (HIPAA §164.312(b)):
//   Every endpoint is wrapped with auditMiddleware that records to the
//   hipaa_audit_logs collection. Recorded:
//     - WHO (actor: userId, email, role) — from req.user/req.session
//     - WHAT (action: clinic.patient.*) — explicit per route
//     - ON WHAT (resourceType: clinic-patient, resourceId from path or null)
//     - WHEN (timestamp — auto)
//     - OUTCOME (success | denied | failure — derived from status code)
//     - WHERE (IP, userAgent, requestId — auto)
//     - METADATA (per route, NEVER includes PHI — only counts/types/flags)
//
//   PHI safety rule for metaFrom: NEVER include firstName, lastName,
//   phone, email, dateOfBirth, notes, or any decrypted content. Audit
//   log must NOT duplicate PHI — otherwise a leaked audit log =
//   leaked patient database. Only safe to log: field names (not
//   values), counts, type enums, booleans.
//
//   EXCEPTION — POST /patients (create):
//     The new patient's _id is generated by the service AFTER middleware
//     runs, so resourceIdFrom cannot capture it. auditMiddleware would
//     fire with resourceId=null and trigger the strict invariant in
//     audit.service.js ("resourceId is required for action ...") and log
//     a warning on every patient creation. To get a real resourceId we
//     call recordActionAsync directly inside the controller AFTER
//     service.createPatient() returns, mirroring the WebSocket pattern
//     used in socket.gateway.js. The middleware is NOT attached to this
//     route — see patient.controller.js → createPatient for the call.

import express from "express";
import * as ctrl from "../controllers/patient.controller.js";
import auditMiddleware from "../../../audit/middleware/auditMiddleware.js";

const router = express.Router();

// ─── Search patients ──────────────────────────────────────────────────
// MUST come before /patients/:id — otherwise "search" is matched as :id.
// We log WHAT TYPE of search was performed (phone/email/lastName), not
// the search value itself — search terms can be PHI.
router.get(
  "/patients/search",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.search",
    metaFrom: (req) => ({
      searchedBy: req.query?.phone
        ? "phone"
        : req.query?.email
          ? "email"
          : req.query?.lastName
            ? "lastName"
            : "unknown",
      limit: Number(req.query?.limit) || 20,
    }),
  }),
  ctrl.searchPatients,
);

// ─── Search DocPats users (for linking) ───────────────────────────────
// Search User accounts to link a patient to. MUST come before
// /patients/:id — otherwise "users" is matched as :id.
//
// PHI operation — searching by date of birth + name. metaFrom logs the
// search MODE (email vs dob) and whether name filters were used, never
// the actual email/dob/name values.
router.get(
  "/patients/users/search",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.user_search",
    metaFrom: (req) => ({
      mode: req.query?.mode || "unknown",
      hasNameFilter: Boolean(req.query?.firstName || req.query?.lastName),
    }),
  }),
  ctrl.searchUsers,
);

// ─── List ─────────────────────────────────────────────────────────────
// No resourceId — this is a collection read. Meta captures pagination
// params (limit, cursor presence) for usage analytics, no PHI.
router.get(
  "/patients",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.list",
    metaFrom: (req) => ({
      limit: Number(req.query?.limit) || 50,
      hasBefore: Boolean(req.query?.before),
      sortBy: req.query?.sortBy || "createdAt",
    }),
  }),
  ctrl.listPatients,
);

// ─── Create ───────────────────────────────────────────────────────────
// NO auditMiddleware here — see header comment above. Audit is recorded
// inside controllers/patient.controller.js → createPatient AFTER the
// service generates the patient._id, so resourceId is real instead of
// null. This avoids the "[audit] async recordAction failed: resourceId
// is required" warning previously seen in prod logs.
router.post("/patients", ctrl.createPatient);

// ─── Read by ID ───────────────────────────────────────────────────────
// Core HIPAA event — "doctor X accessed patient Y's record". This is
// what auditors care about most. resourceId is the patient ID.
router.get(
  "/patients/:id",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.read",
    resourceIdFrom: "params.id",
  }),
  ctrl.getPatient,
);

// ─── Update ───────────────────────────────────────────────────────────
// Meta captures WHICH fields changed (by name) — useful for audit
// reviews. NEVER captures the values (those are PHI). Example log
// after an update: { fieldsChanged: ["phone", "email"] } — we know
// the contact info was changed but not to what.
router.patch(
  "/patients/:id",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.update",
    resourceIdFrom: "params.id",
    metaFrom: (req) => ({
      fieldsChanged: Object.keys(req.body || {}),
    }),
  }),
  ctrl.updatePatient,
);

// ─── Delete (soft) ────────────────────────────────────────────────────
// Critical event — deletion of a PHI record. Always audited.
// Note: this is soft-delete (isDeleted: true), record stays in DB.
router.delete(
  "/patients/:id",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.delete",
    resourceIdFrom: "params.id",
  }),
  ctrl.deletePatient,
);

// ─── Link to DocPats user ─────────────────────────────────────────────
// Sensitive operation — gives a DocPats user account access to this
// patient's record. resourceOwnerId captures WHICH user got linked
// (important for "show me everyone linked to user X's account").
router.post(
  "/patients/:id/link",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.link",
    resourceIdFrom: "params.id",
    resourceOwnerIdFrom: (req) => req.body?.userId,
  }),
  ctrl.linkPatient,
);

// ─── Unlink ───────────────────────────────────────────────────────────
// Inverse of link. The unlinked userId is in the patient doc, not in
// the request — so we can't capture resourceOwnerId at middleware
// level. The action itself + patient ID is sufficient for forensics
// (full state available by querying patient_link history).
router.delete(
  "/patients/:id/link",
  auditMiddleware({
    resourceType: "clinic-patient",
    action: "clinic.patient.unlink",
    resourceIdFrom: "params.id",
  }),
  ctrl.unlinkPatient,
);

export default router;
