// modules/clinic/clinic-medical/pdf/patientCardLabels.js
//
// Подписи разделов печатной медицинской карты.
//
// Отдельным файлом по той же причине, что и подписи рецепта: пять языков
// рядом друг с другом, расхождение видно глазом.

export const CARD_LABELS = {
  ru: {
    genders: { male: "Мужской", female: "Женский", other: "Другой", unknown: "Не указан" },
    title: "Медицинская карта",
    patientDetails: "Данные пациента",
    fullName: "Фамилия, имя",
    dob: "Дата рождения",
    age: "Возраст",
    sex: "Пол",
    weight: "Вес (кг)",
    phone: "Телефон",
    cardNo: "Номер карты",
    allergies: "Аллергии и нежелательные реакции",
    allergiesEmpty: "Не зафиксированы",
    chronic: "Хронические заболевания",
    current: "Принимает сейчас",
    currentEmpty: "Действующих назначений нет",
    encounters: "Последние приёмы",
    labsAbnormal: "Отклонения в анализах",
    operations: "Операции",
    immunization: "Прививки",
    family: "Наследственность",
    empty: "Не зафиксированы",
    generated: "Карта распечатана",
    disclaimer:
      "Выписка собрана из записей карты без пересказа. Полнота зависит от того, что внесено в систему; отсутствие записи в разделе не означает отсутствия факта.",
    noDiagnosis: "без диагноза",
  },
  en: {
    genders: { male: "Male", female: "Female", other: "Other", unknown: "Not stated" },
    title: "Medical record",
    patientDetails: "Patient details",
    fullName: "Full name",
    dob: "Date of birth",
    age: "Age",
    sex: "Sex",
    weight: "Weight (kg)",
    phone: "Phone",
    cardNo: "Record no.",
    allergies: "Allergies and adverse reactions",
    allergiesEmpty: "None recorded",
    chronic: "Chronic conditions",
    current: "Current medication",
    currentEmpty: "No active prescriptions",
    encounters: "Recent encounters",
    labsAbnormal: "Abnormal lab results",
    operations: "Operations",
    immunization: "Immunisations",
    family: "Family history",
    empty: "None recorded",
    generated: "Printed",
    disclaimer:
      "Compiled from record entries without paraphrasing. Completeness depends on what has been entered; an empty section does not mean the absence of the fact.",
    noDiagnosis: "no diagnosis",
  },
  az: {
    genders: { male: "Kişi", female: "Qadın", other: "Digər", unknown: "Göstərilməyib" },
    title: "Tibbi kart",
    patientDetails: "Pasiyent haqqında",
    fullName: "Soyadı, adı",
    dob: "Doğum tarixi",
    age: "Yaş",
    sex: "Cins",
    weight: "Çəki (kq)",
    phone: "Telefon",
    cardNo: "Kart nömrəsi",
    allergies: "Allergiyalar və əks reaksiyalar",
    allergiesEmpty: "Qeyd olunmayıb",
    chronic: "Xroniki xəstəliklər",
    current: "Hazırda qəbul edir",
    currentEmpty: "Aktiv təyinat yoxdur",
    encounters: "Son qəbullar",
    labsAbnormal: "Analizlərdə kənarlaşmalar",
    operations: "Əməliyyatlar",
    immunization: "Peyvəndlər",
    family: "İrsiyyət",
    empty: "Qeyd olunmayıb",
    generated: "Çap edilib",
    disclaimer:
      "Çıxarış kart qeydlərindən dəyişdirilmədən toplanıb. Tamlıq sistemə daxil edilənlərdən asılıdır; boş bölmə faktın olmaması demək deyil.",
    noDiagnosis: "diaqnoz yoxdur",
  },
  tr: {
    genders: { male: "Erkek", female: "Kadın", other: "Diğer", unknown: "Belirtilmemiş" },
    title: "Tıbbi kayıt",
    patientDetails: "Hasta bilgileri",
    fullName: "Adı soyadı",
    dob: "Doğum tarihi",
    age: "Yaş",
    sex: "Cinsiyet",
    weight: "Kilo (kg)",
    phone: "Telefon",
    cardNo: "Kayıt no.",
    allergies: "Alerjiler ve istenmeyen reaksiyonlar",
    allergiesEmpty: "Kayıt yok",
    chronic: "Kronik hastalıklar",
    current: "Şu anda kullandıkları",
    currentEmpty: "Aktif reçete yok",
    encounters: "Son muayeneler",
    labsAbnormal: "Anormal tahlil sonuçları",
    operations: "Ameliyatlar",
    immunization: "Aşılar",
    family: "Aile öyküsü",
    empty: "Kayıt yok",
    generated: "Yazdırıldı",
    disclaimer:
      "Kayıt girdilerinden değiştirilmeden derlenmiştir. Eksiksizlik sisteme girilenlere bağlıdır; boş bölüm olgunun yokluğu anlamına gelmez.",
    noDiagnosis: "tanı yok",
  },
  ar: {
    genders: { male: "ذكر", female: "أنثى", other: "آخر", unknown: "غير محدد" },
    title: "السجل الطبي",
    patientDetails: "بيانات المريض",
    fullName: "الاسم الكامل",
    dob: "تاريخ الميلاد",
    age: "العمر",
    sex: "الجنس",
    weight: "الوزن (كغ)",
    phone: "الهاتف",
    cardNo: "رقم السجل",
    allergies: "الحساسية والتفاعلات الضارة",
    allergiesEmpty: "غير مسجلة",
    chronic: "الأمراض المزمنة",
    current: "الأدوية الحالية",
    currentEmpty: "لا توجد وصفات فعّالة",
    encounters: "آخر الزيارات",
    labsAbnormal: "نتائج مخبرية غير طبيعية",
    operations: "العمليات",
    immunization: "التطعيمات",
    family: "التاريخ العائلي",
    empty: "غير مسجلة",
    generated: "تمت الطباعة",
    disclaimer:
      "جُمعت هذه الخلاصة من قيود السجل دون إعادة صياغة. اكتمالها يعتمد على ما أُدخل في النظام؛ خلو القسم لا يعني انتفاء الواقعة.",
    noDiagnosis: "بدون تشخيص",
  },
};

export default CARD_LABELS;
