// modules/clinic/clinic-medical/pdf/prescriptionFormLabels.js
//
// Подписи полей рецептурного бланка по образцу ВОЗ.
//
// Отдельным файлом, а не внутри prescriptionPdf.js: там уже пять языковых
// объектов на полтораста строк, и дописывать в каждый по два десятка ключей
// значило бы править пять мест сразу. Здесь они лежат рядом друг с другом,
// и расхождение между языками видно глазом.

export const FORM_LABELS = {
  ru: {
    facilityLicence: "Лицензия учреждения №",
    formRef: "Форма",
    patientDetails: "Данные пациента",
    fullName: "Фамилия, имя",
    patientId: "ID пациента",
    age: "Возраст",
    sex: "Пол",
    weight: "Вес (кг)",
    address: "Адрес",
    phone: "Телефон",
    allergies: "Известные аллергии и нежелательные реакции",
    allergiesNone: "Укажите «нет», если аллергий нет",
    prescribedMedication: "Назначенные препараты",
    colMedication: "Препарат (МНН — торговое при необходимости)",
    colStrength: "Дозировка",
    colForm: "Форма",
    colQty: "Кол-во",
    sig: "Приём",
    substitutionAllowed: "Замена на аналог разрешена",
    dispenseAsWritten: "Отпустить как выписано (без замены)",
    repeats: "Повторные отпуски",
    validUntil: "Рецепт действителен до",
    prescriber: "Назначил",
    nameQualification: "ФИО и квалификация",
    registrationNo: "Регистрационный номер / лицензия",
    signatureCaption: "ФИО и подпись врача",
    footnoteTitle: "Стандарт:",
    footnote:
      "Бланк следует ключевым элементам рецепта из руководства ВОЗ «Guide to Good Prescribing»: идентификация врача и учреждения, идентификация пациента, наименование препарата, дозировка, форма и количество, указания по приёму, условия замены и срок действия, подпись врача. Приведите поля в соответствие с требованиями вашей страны перед клиническим применением.",
  },
  en: {
    facilityLicence: "Facility licence no.",
    formRef: "Form ref.",
    patientDetails: "Patient details",
    fullName: "Full name",
    patientId: "Patient ID",
    age: "Age",
    sex: "Sex",
    weight: "Weight (kg)",
    address: "Address",
    phone: "Phone",
    allergies: "Known allergies / adverse reactions",
    allergiesNone: "State NKDA if none known",
    prescribedMedication: "Prescribed medication",
    colMedication: "Medication (INN / generic — brand if required)",
    colStrength: "Strength",
    colForm: "Form",
    colQty: "Qty",
    sig: "Sig",
    substitutionAllowed: "Generic substitution permitted",
    dispenseAsWritten: "Dispense as written (no substitution)",
    repeats: "Repeats / refills",
    validUntil: "Prescription valid until",
    prescriber: "Prescriber",
    nameQualification: "Name & qualification",
    registrationNo: "Registration / licence no.",
    signatureCaption: "Prescriber's name & signature",
    footnoteTitle: "Standard reference:",
    footnote:
      "This form follows the core prescription elements recommended in the WHO Guide to Good Prescribing — prescriber and facility identification, patient identification, inscription (drug, strength, form, quantity), transcription (directions), substitution and validity, and prescriber signature. Adapt fields to your national regulatory requirements before clinical use.",
  },
  az: {
    facilityLicence: "Müəssisə lisenziyası №",
    formRef: "Blank",
    patientDetails: "Pasiyent haqqında",
    fullName: "Soyadı, adı",
    patientId: "Pasiyent ID",
    age: "Yaş",
    sex: "Cins",
    weight: "Çəki (kq)",
    address: "Ünvan",
    phone: "Telefon",
    allergies: "Məlum allergiyalar və əks reaksiyalar",
    allergiesNone: "Yoxdursa «yoxdur» yazın",
    prescribedMedication: "Təyin edilmiş dərmanlar",
    colMedication: "Dərman (BBA — ticarət adı lazım olsa)",
    colStrength: "Doza",
    colForm: "Forma",
    colQty: "Say",
    sig: "Qəbul",
    substitutionAllowed: "Analoqla əvəzləməyə icazə verilir",
    dispenseAsWritten: "Yazıldığı kimi buraxmaq (əvəzsiz)",
    repeats: "Təkrar buraxma",
    validUntil: "Resept etibarlıdır",
    prescriber: "Təyin edib",
    nameQualification: "A.S.A. və ixtisas",
    registrationNo: "Qeydiyyat / lisenziya №",
    signatureCaption: "Həkimin adı və imzası",
    footnoteTitle: "Standart:",
    footnote:
      "Blank ÜST-ün «Guide to Good Prescribing» tövsiyələrinə əsaslanır: həkim və müəssisənin, pasiyentin eyniləşdirilməsi, dərmanın adı, dozası, forması və miqdarı, qəbul göstərişləri, əvəzləmə şərtləri və etibarlılıq müddəti, həkimin imzası. Klinik istifadədən əvvəl sahələri milli tələblərə uyğunlaşdırın.",
  },
  tr: {
    facilityLicence: "Kurum lisans no.",
    formRef: "Form",
    patientDetails: "Hasta bilgileri",
    fullName: "Adı soyadı",
    patientId: "Hasta ID",
    age: "Yaş",
    sex: "Cinsiyet",
    weight: "Kilo (kg)",
    address: "Adres",
    phone: "Telefon",
    allergies: "Bilinen alerjiler / istenmeyen reaksiyonlar",
    allergiesNone: "Yoksa «yok» yazın",
    prescribedMedication: "Reçete edilen ilaçlar",
    colMedication: "İlaç (etkin madde — gerekirse ticari ad)",
    colStrength: "Doz",
    colForm: "Form",
    colQty: "Adet",
    sig: "Kullanım",
    substitutionAllowed: "Eşdeğer ile değişime izin verilir",
    dispenseAsWritten: "Yazıldığı gibi verilsin (değiştirmeden)",
    repeats: "Tekrar sayısı",
    validUntil: "Reçete geçerlilik tarihi",
    prescriber: "Reçete eden",
    nameQualification: "Ad soyad ve unvan",
    registrationNo: "Kayıt / lisans no.",
    signatureCaption: "Hekimin adı ve imzası",
    footnoteTitle: "Standart:",
    footnote:
      "Bu form Dünya Sağlık Örgütü'nün «Guide to Good Prescribing» önerilerini izler: hekim ve kurum kimliği, hasta kimliği, ilaç adı, dozu, formu ve miktarı, kullanım talimatı, değişim koşulları ve geçerlilik, hekim imzası. Klinik kullanımdan önce alanları ulusal mevzuata uyarlayın.",
  },
  ar: {
    facilityLicence: "رقم ترخيص المنشأة",
    formRef: "نموذج",
    patientDetails: "بيانات المريض",
    fullName: "الاسم الكامل",
    patientId: "رقم المريض",
    age: "العمر",
    sex: "الجنس",
    weight: "الوزن (كغ)",
    address: "العنوان",
    phone: "الهاتف",
    allergies: "الحساسية والتفاعلات الضارة",
    allergiesNone: "اكتب «لا يوجد» عند عدم وجودها",
    prescribedMedication: "الأدوية الموصوفة",
    colMedication: "الدواء (الاسم العلمي)",
    colStrength: "الجرعة",
    colForm: "الشكل",
    colQty: "الكمية",
    sig: "الاستعمال",
    substitutionAllowed: "يُسمح بالبديل الجنيس",
    dispenseAsWritten: "يُصرف كما كُتب دون بديل",
    repeats: "مرات الصرف",
    validUntil: "الوصفة صالحة حتى",
    prescriber: "الطبيب الواصف",
    nameQualification: "الاسم والاختصاص",
    registrationNo: "رقم التسجيل / الترخيص",
    signatureCaption: "اسم الطبيب وتوقيعه",
    footnoteTitle: "المعيار:",
    footnote:
      "يتبع هذا النموذج توصيات منظمة الصحة العالمية «Guide to Good Prescribing»: تعريف الطبيب والمنشأة، تعريف المريض، اسم الدواء وجرعته وشكله وكميته، تعليمات الاستعمال، شروط الاستبدال والصلاحية، وتوقيع الطبيب.",
  },
};
