// server/modules/simulation/validators/landmarksValidator.js
//
// S.7.5+ — расширенная валидация landmarks-payload.
//
// Изменения относительно версии S.7.3:
//   • Длина массива: 0..600 (было: 0 или 468). Запас под manual точки
//     и MediaPipe Tasks Web v2 (478 точек включая iris).
//   • mediapipeIndex: -1 (manual) или 0..477.
//     Уникальность проверяется только для авто-точек (≥0).
//   • Новые группы: forehead, cheeks, jaw, chin, ears, manual.
//   • Поля hidden и autoGenerated сохраняются с клиента
//     (раньше autoGenerated был захардкожен в true → ломало manual).
//   • z поле теперь опциональное (MediaPipe Tasks Web v2 может не давать z).

const ALLOWED_GROUPS = new Set([
  "face_oval",
  "forehead",
  "nose",
  "lips",
  "left_eye",
  "right_eye",
  "left_eyebrow",
  "right_eyebrow",
  "left_cheek",
  "right_cheek",
  "left_jaw",
  "right_jaw",
  "chin",
  "ears",
  "manual",
  "other",
]);

const MAX_LANDMARKS = 600;
const MAX_MEDIAPIPE_INDEX = 477; // v2 = 0..477 (468 face + 10 iris)

/**
 * Валидирует и нормализует массив landmarks.
 * Возвращает санитизированный массив.
 *
 * @param {unknown} input
 * @returns {Array<Object>} sanitized landmarks
 * @throws {Error} если payload невалиден
 */
export function validateLandmarks(input) {
  if (!Array.isArray(input)) {
    throw new Error("landmarks must be an array");
  }

  if (input.length > MAX_LANDMARKS) {
    throw new Error(
      `landmarks too many: ${input.length} (max ${MAX_LANDMARKS})`,
    );
  }

  const seenAutoIndexes = new Set();
  const seenIds = new Set();
  const result = [];

  for (let i = 0; i < input.length; i++) {
    const lm = input[i];
    if (!lm || typeof lm !== "object") {
      throw new Error(`landmarks[${i}] is not an object`);
    }

    const { id, mediapipeIndex, group, x, y, z, hidden, autoGenerated } = lm;

    /* ─── id ─── */
    if (typeof id !== "string" || id.length === 0 || id.length > 64) {
      throw new Error(`landmarks[${i}].id invalid`);
    }
    if (seenIds.has(id)) {
      throw new Error(`landmarks[${i}].id duplicate: ${id}`);
    }
    seenIds.add(id);

    /* ─── mediapipeIndex ─── */
    // -1 для manual landmarks, 0..477 для авто
    if (
      !Number.isInteger(mediapipeIndex) ||
      mediapipeIndex < -1 ||
      mediapipeIndex > MAX_MEDIAPIPE_INDEX
    ) {
      throw new Error(
        `landmarks[${i}].mediapipeIndex invalid: ${mediapipeIndex}`,
      );
    }

    // Уникальность только для авто-точек (manual могут все иметь -1)
    if (mediapipeIndex >= 0) {
      if (seenAutoIndexes.has(mediapipeIndex)) {
        throw new Error(
          `landmarks[${i}].mediapipeIndex duplicate: ${mediapipeIndex}`,
        );
      }
      seenAutoIndexes.add(mediapipeIndex);
    }

    /* ─── group ─── */
    if (!ALLOWED_GROUPS.has(group)) {
      throw new Error(`landmarks[${i}].group invalid: ${group}`);
    }

    /* ─── x, y (обязательные) ─── */
    if (
      typeof x !== "number" ||
      !Number.isFinite(x) ||
      x < 0 ||
      x > 1 ||
      typeof y !== "number" ||
      !Number.isFinite(y) ||
      y < 0 ||
      y > 1
    ) {
      throw new Error(`landmarks[${i}] coordinates x/y invalid`);
    }

    /* ─── z (опциональный) ─── */
    let zSafe = 0;
    if (z != null) {
      if (typeof z !== "number" || !Number.isFinite(z)) {
        throw new Error(`landmarks[${i}].z invalid`);
      }
      zSafe = z;
    }

    /* ─── hidden (опциональный boolean) ─── */
    const hiddenSafe = typeof hidden === "boolean" ? hidden : false;

    /* ─── autoGenerated (опциональный boolean, default true) ─── */
    // Manual landmarks приходят с autoGenerated=false и mediapipeIndex=-1
    let autoGeneratedSafe;
    if (typeof autoGenerated === "boolean") {
      autoGeneratedSafe = autoGenerated;
    } else {
      // Если поле не пришло — выводим из mediapipeIndex
      autoGeneratedSafe = mediapipeIndex >= 0;
    }

    // Sanity check: manual точки должны иметь mediapipeIndex=-1,
    // и наоборот — авто-точки должны иметь индекс ≥0.
    if (autoGeneratedSafe && mediapipeIndex < 0) {
      throw new Error(
        `landmarks[${i}] inconsistent: autoGenerated=true but mediapipeIndex=${mediapipeIndex}`,
      );
    }
    if (!autoGeneratedSafe && mediapipeIndex >= 0) {
      throw new Error(
        `landmarks[${i}] inconsistent: autoGenerated=false but mediapipeIndex=${mediapipeIndex}`,
      );
    }

    /* ─── Sanitized output ─── */
    result.push({
      id,
      mediapipeIndex,
      group,
      x,
      y,
      z: zSafe,
      hidden: hiddenSafe,
      autoGenerated: autoGeneratedSafe,
    });
  }

  return result;
}

/**
 * Валидирует metadata о детекции.
 */
export function validateLandmarksMeta(input) {
  if (input == null) {
    return { modelVersion: null, imageWidth: null, imageHeight: null };
  }
  if (typeof input !== "object") {
    throw new Error("landmarksMeta must be an object");
  }

  const { modelVersion, imageWidth, imageHeight } = input;

  const sanitizedModelVersion =
    typeof modelVersion === "string" && modelVersion.length <= 64
      ? modelVersion
      : null;

  const sanitizedW =
    Number.isInteger(imageWidth) && imageWidth > 0 && imageWidth <= 20000
      ? imageWidth
      : null;
  const sanitizedH =
    Number.isInteger(imageHeight) && imageHeight > 0 && imageHeight <= 20000
      ? imageHeight
      : null;

  return {
    modelVersion: sanitizedModelVersion,
    imageWidth: sanitizedW,
    imageHeight: sanitizedH,
  };
}
