// modules/clinic/clinic-staff/routes/staff.routes.js
//
// REST endpoints for ClinicMembership management (staff = clinic members).
//
// Mount path (from parent clinic router): /api/v1/clinic/*
// Final URLs:
//   GET    /api/v1/clinic/staff/search-doctors
//   GET    /api/v1/clinic/staff
//   POST   /api/v1/clinic/staff
//   PATCH  /api/v1/clinic/staff/:id/role
//   DELETE /api/v1/clinic/staff/:id
//
// AUDIT MIDDLEWARE (HIPAA §164.312(b)):
//   Every endpoint is audited to hipaa_audit_logs. Staff actions are
//   PHI-adjacent (membership data + decrypted PII names/emails of
//   medical staff) — auditing these is required for compliance.
//
//   PHI safety rule for metaFrom: never log decrypted names, emails,
//   or phone numbers. Safe to log: role names (business permission,
//   not PHI), counts, structural flags.

import express from "express";
import * as ctrl from "../controllers/staff.controller.js";
import auditMiddleware from "../../../audit/middleware/auditMiddleware.js";

const router = express.Router();

// ─── Doctor search ────────────────────────────────────────────────────
// Used by the "Add staff" flow to find existing DocPats users to
// invite as clinic staff. Returns doctor profiles (public/professional
// info, not PHI of patients).
//
// MUST come before /staff to avoid /:id collision in any nested router.
router.get(
  "/staff/search-doctors",
  auditMiddleware({
    resourceType: "clinic-employee",
    action: "clinic.staff.list",
    metaFrom: (req) => ({
      // What kind of query was used — but not the value itself.
      // Doctor names are professional info (not PHI), but search
      // strings can contain typos / partial PII so safer to omit.
      searchedBy: req.query?.email
        ? "email"
        : req.query?.name
          ? "name"
          : req.query?.specialization
            ? "specialization"
            : "unknown",
      limit: Number(req.query?.limit) || 10,
    }),
  }),
  ctrl.searchDoctors,
);

// ─── List staff ───────────────────────────────────────────────────────
// Returns all clinic members with decrypted PII (names, emails of staff).
// This is a HIPAA-loggable event — auditor needs to know who pulled
// the full staff list.
//
// resourceId is intentionally omitted: clinic.staff.list is a
// collection-scope action (audit.service whitelists *.list).
router.get(
  "/staff",
  auditMiddleware({
    resourceType: "clinic-employee",
    action: "clinic.staff.list",
    metaFrom: (req) => ({
      limit: Number(req.query?.limit) || 50,
      hasFilter: Boolean(req.query?.role || req.query?.status),
      roleFilter: req.query?.role || null,
    }),
  }),
  ctrl.listStaff,
);

// ─── Add staff member ─────────────────────────────────────────────────
// Adds an existing DocPats user (or creates a ClinicEmployee record)
// to this clinic with a specified role. Critical event — grants access
// to clinic-level PHI for the new staff member.
//
// HIPAA AUDIT IDENTITY (16 May 2026):
//   The new ClinicMembership._id is not known to the middleware (it's
//   generated by the service AFTER the handler runs). For audit forensics
//   the meaningful identity of the resource is the USER receiving access,
//   so we use req.body.userId as resourceId. resourceOwnerId is the same
//   value — it records WHO got the new access.
//
//   This was previously missing, causing audit.recordAction to throw
//   "resourceId is required for action clinic.staff.add" on every staff
//   add — silent HIPAA compliance gap (warned, not enforced).
router.post(
  "/staff",
  auditMiddleware({
    resourceType: "clinic-employee",
    action: "clinic.staff.add",
    resourceIdFrom: (req) => req.body?.userId,
    resourceOwnerIdFrom: (req) => req.body?.userId,
    metaFrom: (req) => ({
      // Role is business permission, not PHI — safe to log.
      role: req.body?.role || null,
      // Whether this was a User link or a new ClinicEmployee.
      actorType: req.body?.userId ? "user" : "employee",
    }),
  }),
  ctrl.addStaff,
);

// ─── Change role ──────────────────────────────────────────────────────
// Privilege escalation/de-escalation — critical for security audit.
// "Who promoted X to admin?" is a textbook HIPAA forensics query.
//
// resourceIdFrom uses a function (not a dot-path string) so we can fall
// back to alternate param names if the route is ever remounted with a
// different param key. params.id is the canonical mount.
router.patch(
  "/staff/:id/role",
  auditMiddleware({
    resourceType: "clinic-employee",
    action: "clinic.staff.role_change",
    resourceIdFrom: (req) =>
      req.params?.id || req.params?.staffId || req.params?.membershipId,
    metaFrom: (req) => ({
      newRole: req.body?.role || null,
    }),
  }),
  ctrl.updateStaffRole,
);

// ─── Remove staff ─────────────────────────────────────────────────────
// Soft-remove. The membership record stays in DB (isRemoved: true)
// for audit/compliance reasons — never hard-delete staff records.
router.delete(
  "/staff/:id",
  auditMiddleware({
    resourceType: "clinic-employee",
    action: "clinic.staff.remove",
    resourceIdFrom: (req) =>
      req.params?.id || req.params?.staffId || req.params?.membershipId,
  }),
  ctrl.removeStaff,
);

export default router;
